# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Get google secrets
        env:
          DATA: ${{ secrets.FIRESTORE }}
        run: echo $DATA | base64 -di > firestore.json

      - name: Build
        run: go build -v ./...

      - name: Test Number Generator
        run: go test -v ./utils -count 10000 -failfast
